# Generated by Django 3.0.7 on 2020-06-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=250)),
                ('department_head', models.CharField(max_length=250)),
                ('number_of_staffs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('other_name', models.CharField(max_length=250)),
                ('current_age', models.IntegerField()),
                ('sex', models.CharField(choices=[['Male', 'Male'], ['Female', 'Female']], max_length=25)),
                ('nationality', models.CharField(max_length=150)),
                ('residential_state', models.CharField(max_length=150)),
                ('residential_lga', models.CharField(max_length=150)),
                ('residential_town', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=150)),
                ('state_of_birth', models.CharField(max_length=150)),
                ('lga_of_birth', models.CharField(max_length=150)),
                ('diabled', models.CharField(choices=[['Yes', 'Yes'], ['No', 'No']], max_length=25)),
                ('work_status', models.CharField(choices=[['Employed', 'Employed'], ['Unemployed', 'Unemployed']], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=250)),
                ('state_zone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[['Male', 'Male'], ['Female', 'Female']], max_length=25)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('highest_qualification', models.CharField(max_length=25)),
                ('school_attended', models.CharField(max_length=250)),
                ('result_obtained', models.CharField(max_length=150)),
                ('other_qualification', models.CharField(max_length=255)),
                ('professional_qualification', models.CharField(max_length=250)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_name', models.CharField(max_length=250)),
                ('lga_zone', models.CharField(max_length=15)),
                ('lga_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='core.State')),
            ],
        ),
    ]
