# Generated by Django 3.0.7 on 2020-06-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='date_of_creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
