# Generated by Django 3.0.7 on 2020-06-28 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_date_of_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='highest_qualification',
            new_name='higher_qualification',
        ),
        migrations.AddField(
            model_name='staff',
            name='DOB',
            field=models.DateField(default=datetime.date(2020, 6, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='date_obtained',
            field=models.DateField(default=datetime.date(2020, 6, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 6, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='Ilogu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='other_name',
            field=models.CharField(default='Chukwuma', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 6, 28)),
            preserve_default=False,
        ),
    ]
