# Generated by Django 3.0.7 on 2020-07-09 22:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200628_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='diabled',
            new_name='disabled',
        ),
        migrations.AddField(
            model_name='person',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2020, 7, 9, 22, 17, 23, 517086)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='lga_of_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lga_of_birth', to='core.LGA'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residential_lga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_lga', to='core.LGA'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residential_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_state', to='core.State'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state_of_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_of_birth', to='core.State'),
        ),
    ]
